### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/openethereum-3.x#51]
Fix all existing unit tests

**Comment by dforsten** [comment]
Pull Request submitted!

**Comment by dforsten** [comment]
failures:
    tests::chain::disconnect_on_unrelated_chain
    tests::chain::empty_blocks
    tests::chain::forked
    tests::chain::forked_with_misbehaving_peer
    tests::chain::long_chain
    tests::chain::net_hard_fork
    tests::chain::propagate_blocks
    tests::chain::propagate_hashes
    tests::chain::restart
    tests::chain::restart_on_malformed_block
    tests::chain::status_packet
    tests::chain::two_peers
    tests::consensus::authority_round
    tests::snapshot::snapshot_sync

**Comment by SurfingNerd** [comment]
fixed with https://github.com/DMDcoin/openethereum-3.x/pull/83
