### ISSUE TITLE
slow down block production during key generation.

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/openethereum-3.x#74]
in the current implmentation  <= v0.8  the Network starts to create blocks as fast as possible during the key generation.
The fastest a network can run is 1 block per second (capped by blocktime granularity of 1 second).
Networks that cannot achieve this tempo, end up in a situation were the fast 2/3 nodes needed for consensus sprint as fast as possible, while the slower 1/3  of the nodes do not manage to keep up, therefore also never manage to be at the Tip in order to process the Key-Generation.
Proposal: await the regular Minimum Block Time.

**Comment by cryptonit** [comment]
so the proposal is to have the normal min blocktime also in the keygeneration phase too?
in my opinion thats as designed anyway if it works different its not intendet.

basically the fastest 2/3 of nodes decide how fast we can create blocks thats fine
in normal operation

in case we have time critical messages in key generation phase where we need any node be able answer in time
we can think about a slower min blocktime just for this timewindow

but we also need to keep in mind its desired that the validator candidates run on good enough servers

so be able dedect what nodes are to weak and punsih them by remove from active set is also a valid way

**Comment by SurfingNerd** [comment]
@cryptonit yes i mean it that way, that is a very good summary. i have started to work on it.

**Comment by SurfingNerd** [comment]
Key generation is now at a 15 seconds interval on the testnet.
It is a noticable improvement, but there are other reasons why a node can fail it's key generation.
